### PR TITLE
Can convert retry time cycle to retries now

### LINKED ISSUE #87: Convert RetryTimeCycle to Retries
### Describe the bug

I have a service task with asyncBefore and RetryTimeCycle `R4/PT10S`. 

Hint after conversion says: 

```
TASK: Element 'failedJobRetryTimeCycle' was transformed, please review. Hint: Retry time cycle works different in Zeebe. Please review your implementation
```

But the retries on the task definition of the converted process is still empty. 

### Steps to reproduce

Convert a process model with a service task with async before and retryTimeCycle set.

### Expected Behaviour

The retries on the converted process is set to `4`.

The hint is adjusted.

Or change the hint to ' ... is removed' .

### Library version

0.1.2-SNAPSHOT

### Camunda version

7

### Camunda Distribution

other

### Other Camunda distribution

_No response_

### PR DESCRIPTION
**Pull request by jonathanlukas**
## Description
Until now, the Retry Time Cycle was marked as task for manual translation. Now, the retry time cycle is converted automatically, providing a task with additional information on how to implement timeouts.

## Additional context
Closes #87 

## Testing your changes
There is a test in place that covers valid retry time cycle expressions

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an existing open issue)
- [x] New feature (non-breaking change which adds functionality to an extension)
- [ ] Breaking change (fix or feature that would cause existing functionality of an extension to change)
- [ ] Documentation update (changes made to an existing piece of documentation)

## Checklist:
- [x] My code adheres to the syntax used by this extension.
- [ ] My pull request requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **Camunda Community Hub** documentation.
- [x] I have read the **Pull Request Process** documentation.
- [x] I have added or suggested tests to cover my changes suggested in this pull request.
- [x] All new and existing CI/CD tests passed.
- [x] I will /assign myself this issue, and add the relevant [issue labels] to it if they are not automatically generated by Probot.
- [x] I will tag @camunda-community-hub/devrel in a new comment on this issue if 30 days have passed since my pull request was opened and I have not received a response from the extension's maintainer.

### CODE REVIEW

**Comment by ingorichtsmeier** [comment]
This duration helper offers the same as : https://github.com/camunda/camunda-bpm-platform/blob/master/engine/src/main/java/org/camunda/bpm/engine/impl/calendar/DurationHelper.java.

What about reuse/copy this implementation (with relevant Junit Tests)?

**Comment by jonathanlukas** [comment]
The purpose of the DurationHelper is different.

Also, I think the provided implementation does what it should do as it only serves the purpose of extracting a retry number from an expression.

I would suggest to add more tests to make this more resistent.

File: backend-diagram-converter/core/src/main/resources/message-templates.properties [hunk 1]
```diff
@@ -43,7 +43,8 @@ connector-id={{ templates.element-transformed-prefix }} Connector id is transfor
 property={{ templates.element-transformed-prefix }} Property '{{ propertyName}}' lives in the Zeebe namespace now.
 execution-listener={{ templates.element-not-transformable-prefix }} Execution Listeners do not exist in Zeebe.
 task-listener={{ templates.element-not-transformable-prefix }} Task Listeners do not exist in Zeebe.
-failed-job-retry-time-cycle={{ templates.element-not-transformable-prefix }} The timecycle '{{ timecycle }}' has to be transformed to Retries.
+failed-job-retry-time-cycle={{ templates.element-transformed-prefix }} The timecycle '{{ timecycle }}' was transformed to '{{ retries }}' retries. Please review. Please keep in mind that the timeout between the retries has to be defined by your worker implementation.
```
Comment (ingorichtsmeier) [inline backend-diagram-converter/core/src/main/resources/message-templates.properties:46]: > Please keep in mind that the timeout between the retries has to be defined by your worker implementation

Why not provide the duration in a header to the worker?

Comment (jonathanlukas) [reply backend-diagram-converter/core/src/main/resources/message-templates.properties:46]: This is a good idea.

File: backend-diagram-converter/core/src/test/java/org/camunda/community/converter/RetryTimeCycleConverterTest.java [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+import static org.junit.jupiter.api.Assertions.*;
+
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.CsvSource;
+
+public class RetryTimeCycleConverterTest {
+
+  @ParameterizedTest
+  @CsvSource(
+      value = {"R5/PT1S; 5", "PT3S, PT4S, PT5S; 3", "R5/PT1S, PT10M; 6"},
```
Comment (ingorichtsmeier) [inline backend-diagram-converter/core/src/test/java/org/camunda/community/converter/RetryTimeCycleConverterTest.java:12]: > "R5/PT1S, PT10M; 6"

This combination is not possible: https://camunda.slack.com/archives/C80C0EC79/p1668083409447289

Comment (jonathanlukas) [reply backend-diagram-converter/core/src/test/java/org/camunda/community/converter/RetryTimeCycleConverterTest.java:12]: Good to know, I was not sure. So the function can do more than it could.

Comment (ingorichtsmeier) [reply backend-diagram-converter/core/src/test/java/org/camunda/community/converter/RetryTimeCycleConverterTest.java:12]: Copy the original implementation? We should not add functionality that is not implemented in the Camunda Platform 7.

Comment (jonathanlukas) [reply backend-diagram-converter/core/src/test/java/org/camunda/community/converter/RetryTimeCycleConverterTest.java]: Removed functionality. Instead, focus on robust implementation.

File: backend-diagram-converter/core/src/main/java/org/camunda/community/converter/RetryTimeCycleConverter.java [hunk 3]
```diff
@@ -1,25 +1,58 @@
...
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 public class RetryTimeCycleConverter {
+  private static final Logger LOG = LoggerFactory.getLogger(RetryTimeCycleConverter.class);
   private static final Pattern PATTERN = Pattern.compile("R(\\d*)/");
+  private static final Pattern DURATION_PATTERN = Pattern.compile("(P.*)");
 
-  public static int convert(String timecycle) {
+  public static List<String> convert(String timecycle) {
```
Comment (ingorichtsmeier) [inline backend-diagram-converter/core/src/main/java/org/camunda/community/converter/RetryTimeCycleConverter.java:18]: Who knows, what the list contains? (except you as implementor).

The process engine implementation offers getters for all important parts...

Comment (jonathanlukas) [reply backend-diagram-converter/core/src/main/java/org/camunda/community/converter/RetryTimeCycleConverter.java:30]: Added an explanation
