### PR TITLE
Bugfix: CLI converter would copy C8 bpmn diagrams

### LINKED ISSUE #69: Converter CLI exports not-converted diagrams
### Describe the bug

When trying to convert C8 diagrams, the converter should not export them anymore. 

However, it does.

### Steps to reproduce

1. Build the converter
2. Use it on a repo with C8 diagrams
3. They are "converted". This should not happen

### Expected Behaviour

The converter should notify that a diagram was not converted and will not be exported.

### Library version

latest

### Camunda version

x

### Camunda Distribution

other

### Other Camunda distribution

x

### PR DESCRIPTION
**Pull request by jonathanlukas**
## Description
In the previous version, the CLI tool would create new diagrams, even if it should not.
This was the case for C8 diagrams.

Trivia: Somehow the ServiceLoader was not able to locate the required Implementation of the NotificationService, maybe because of the packaging.

Closes #69 

## Testing your changes
There was a test introduced in the converter core library that asserted that an exception can be thrown outside the converter (using the notify implementation).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an existing open issue)
- [ ] New feature (non-breaking change which adds functionality to an extension)
- [ ] Breaking change (fix or feature that would cause existing functionality of an extension to change)
- [ ] Documentation update (changes made to an existing piece of documentation)

## Checklist:
- [x] My code adheres to the syntax used by this extension.
- [ ] My pull request requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **Camunda Community Hub** documentation.
- [x] I have read the **Pull Request Process** documentation.
- [ ] I have added or suggested tests to cover my changes suggested in this pull request.
- [x] All new and existing CI/CD tests passed.
- [x] I will /assign myself this issue, and add the relevant [issue labels] to it if they are not automatically generated by Probot.
- [x] I will tag @camunda-community-hub/devrel in a new comment on this issue if 30 days have passed since my pull request was opened and I have not received a response from the extension's maintainer.

### CODE REVIEW

File: backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/PrintNotificationServiceImpl.java [hunk 1]
```diff
@@ -5,8 +5,8 @@
 public class PrintNotificationServiceImpl implements NotificationService {
```
Comment (ingorichtsmeier) [inline backend-diagram-converter/cli/src/main/java/org/camunda/community/converter/cli/PrintNotificationServiceImpl.java:5]: Use logger instead of System.out.println

**Review by ingorichtsmeier — CHANGES_REQUESTED** [review]
improve logging, remove sysout

**Comment by ingorichtsmeier** [comment]
All good now, LGTM
